PACKAGE_NAME="claw-msi-wmi-platform"
PACKAGE_VERSION="0.1.1"

BUILT_MODULE_NAME[0]="msi-wmi-platform"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make KERNELRELEASE=${kernelver}"
AUTOINSTALL="yes"
